jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Debugging
        run: echo "DEBUG: Enabling Docker Debug Mode"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/firstpipeline:latest
